apiVersion: apps/v1
kind: Deployment
metadata:
  name: alameda-analyzer
  namespace: {{.NameSpace}}
  labels:
    app: alameda
    component: alameda-analyzer
spec:
  selector:
    matchLabels:
      app: alameda
      component: alameda-analyzer
  replicas: 1
  template:
    metadata:
      labels:
        app: alameda
        component: alameda-analyzer
    spec:
      serviceAccountName: alameda-analyzer
      containers:
      - name: alameda-analyzer
        image: quay.io/prophetstor/alameda-analyzer-ubi:v0.3.54
        imagePullPolicy: Always
        readinessProbe:
          exec:
            command:
            - /usr/local/bin/alameda-analyzer
            - probe
            - --type=readiness
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/alameda-analyzer
            - probe
            - --type=liveness
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
          - name: NAMESPACE_NAME
            value: "{{.NameSpace}}"
          - name: FEDERATORAI_ANALYSIS_DATAHUB_ADDRESS
            value: "alameda-datahub.{{.NameSpace}}.svc"
          - name: FEDERATORAI_ANALYSIS_DATAHUB_PORT
            value: "50050"
          - name: FEDERATORAI_ANALYSIS_OUTLIER_SETTING_DBSCAN_EPS
            value: "0.3"
          - name: FEDERATORAI_ANALYSIS_OUTLIER_SETTING_DBSCAN_MINPTS
            value: "5"
          - name: FEDERATORAI_ANALYSIS_OUTLIER_SETTING_DETECT_LEVEL
            value: "6"
          - name: FEDERATORAI_ANALYSIS_OUTLIER_SETTING_DETECT_DELAY
            value: "60"
          - name: FEDERATORAI_ANALYSIS_OUTLIER_SETTING_OBSERVED_SIZE
            value: "120"
          - name: FEDERATORAI_ANALYSIS_OUTLIER_DETECT_GPU
            value: "true"
      volumes:
        - name: alameda-analyzer-data-storage
        - name: alameda-analyzer-log-storage
