apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.NameSpace}}-alameda-analyzer
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - autoscaling.containers.ai
  resources:
  - "*"
  verbs:
  - get
  - list